# 用于将静态内容部署到 GitHub Pages 的简单工作流
name: 部署静态内容到 Pages

on:
  # 运行在推送到默认分支时
  push:
    branches: ["main"]

  # 允许从 Actions 标签手动运行此工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 仅允许一个并发部署，跳过在进行中和最新排队之间排队的运行。
# 但是，不要取消进行中的运行，因为我们希望允许这些生产部署完成。
concurrency:
  group: "pages"
  cancel-in-progress: false

  # 单一部署任务，因为我们只是部署
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: npm install && npm run build

    - name: Deploy to Gitee Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITEE_TOKEN }}
        external_repository: your-gitee-username/your-repo-name
        publish_dir: ./dist
